name: GH-build-DEV
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      ## Debugmail.io
      - name: Send mail
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ secrets.EMAIL_HOST }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_LOGIN }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Testing email sending in GitHub Actions workflow
          to: bejose34@gmail.com
          from: José Becerra
          body: Build job of ${{ github.repository }} completed successfully!
