
name: GH-build-DEV

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x
    - name: Restore dependencies
      with:
        dotnet-version: 8.x
        cache: true
    - run: dotnet restore --locked-mode
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
