
name: GH-build-DEV

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: ${{ matrix.dotnet-version }}
    - name: Display dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Send mail
      uses: dawidd6/action-send-mail@v6      
      with:                
        # Required mail server address if not connection_url:
        server_address: ${{ secrets.EMAIL_HOST }}
        # Server port, default 25:
        server_port: ${{ secrets.EMAIL_PORT }}        
        # Optional (recommended) mail server username:
        username: ${{ secrets.EMAIL_LOGIN }}
        # Optional (recommended) mail server password:
        password: ${{ secrets.EMAIL_PASS }}
        # Required mail subject:
        subject: Test Github Actions Send Email
        # Required recipients' addresses:
        to: bejose34@gmail.com
        # Required sender full name (address can be skipped):
        from: José Becerra
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!       
