name: GH-docker-deploy-DEV

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Login Registry
      run: docker login ghcr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_TOKEN }}
    
    - name: Build and tag Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ secrets.REGISTRY_USERNAME }}/appdocker:latest
    
    - name: Push image to Registry
      run: docker push ghcr.io/${{ secrets.REGISTRY_USERNAME }}/appdocker:latest
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_URL }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/AcademiaNovit2025
          docker compose pull
          docker compose up -d
